#!/bin/bash
# this script is used on hack.p6c.org as the 'examples.perl6.org' user to update
# the website.

set -e
set -x
. /home/rakudobrew/rakudobrew-bash

ulimit -v 2097152   # 2 GB
ulimit -t 3600      # 1 hour

cd ~/perl6-examples
git fetch
before=$(git rev-parse HEAD)
git checkout origin/master
after=$(git rev-parse HEAD)
if [ "$before" = "$after" ]
then
	echo "nothing to do"
else
    LOGDIR=$HOME/perl6-examples/html/build-log
    mkdir -p "$LOGDIR"
    DATE=$(date --iso-8601=minutes)
    LOGFILE="$LOGDIR/build-$DATE.log"
    echo "Writing logs to $LOGFILE"
    exec >$LOGFILE 2>&1

    echo 'Cleaning out old HTML files'
    # don't clean out html/ entirely, because there are some files
    # under version control there, and because  of html/build-log/
    find html/ -name '*.html' -delete

    # if the htmilfy fails, sync the build log.
    # since sync-build-log returns false, not the whole thing is synced
    time make html || ./util/sync-build-log
    ./util/sync
fi

# vim: expandtab shiftwidth=4
